### ISSUE TITLE
Packaging Error

### ISSUE THREAD

**Issue by mkygogo** [rezonated/openai-unreal#4]
ue5.1 ,try to package the project, got error: 

```
UATHelper: Packaging (Windows): LogInit: Display: LogCoreRedirects: Error: AddRedirect(F:/OpenAiUnreal/Saved/Config/WindowsEditor/UnrealOpenAI.ini) found conflicting redirects for /Script/UnrealOpenAI.FunctionalTestPawn:StartCreateFilesTest! Old: /Script/UnrealOpenAI.FunctionalTestPawn:StartCreateFilesURLTest, New: /Script/UnrealOpenAI.FunctionalTestPawn:StartCreateFileTest
UATHelper: Packaging (Windows): LogInit: Display: LogCoreRedirects: Error: AddRedirect(F:/OpenAiUnreal/Saved/Config/WindowsEditor/UnrealOpenAI.ini) found conflicting redirects for /Script/UnrealOpenAI.FunctionalTestPawn:CompletionFunctionalTest! Old: /Script/UnrealOpenAI.FunctionalTestPawn:CreateCompletionFunctionalTest, New: /Script/UnrealOpenAI.FunctionalTestPawn:CompletionsFunctionalTest
```

**Comment by rezonated** [comment]
Hello, have you solved this issue? 
If you have not, can you upload your project files so I can have a look?

Thanks.

**Comment by mkygogo** [comment]
I fixed it by deleting two lines, in the DefaultUnrealOpenAI.ini
FunctionRedirects=(OldName="/Script/UnrealOpenAI.FunctionalTestPawn.StartCreateFilesTest",NewName="/Script/UnrealOpenAI.FunctionalTestPawn.StartCreateFileTest")
PropertyRedirects=(OldName="/Script/UnrealOpenAI.FunctionalTestPawn.CompletionFunctionalTest",NewName="/Script/UnrealOpenAI.FunctionalTestPawn.CompletionsFunctionalTest")
